### ISSUE TITLE
Remove unnecessary vite.config.js file

### ISSUE THREAD

**Issue by halivert** [halivert/interactive-pricing-component#2]

**Comment by varnaa** [comment]
Hey, i'd like to work on this issue.

**Comment by varnaa** [comment]
@halivert  is this issue acceptable for hacktoberfest ??

**Comment by mingweisoo** [comment]
I would like to work on this issue

**Comment by halivert** [comment]
> @halivert  is this issue acceptable for hacktoberfest ??

Is too easy for hacktoberfest, but you can practice for it.
